//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> ArtistSet { get; set; }
        public virtual DbSet<Album> AlbumSet { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<Show> ShowSet { get; set; }
        public virtual DbSet<AudioFile> AudioFileSet { get; set; }
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<Apps> AppsSet { get; set; }
        public virtual DbSet<Permisos> PermisosSet { get; set; }
        public virtual DbSet<Noticies> NoticiesSet { get; set; }
        public virtual DbSet<NewsCatego> NewsCategoSet { get; set; }
    }
}
