//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticies
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string HTML { get; set; }
    
        public virtual NewsCatego NotCatego { get; set; }
    }
}
