//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podcast : AudioFile
    {
        public bool isPublic { get; set; }
        public bool Uploaded { get; set; }
        public System.DateTime AirDateTime { get; set; }
    }
}
